name: Build website and publish to S3

on:
  push:
    branches: [ "main" ]

env:
  node-version: 22.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{env.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{env.node-version}}
        cache: 'npm'
    - run: npm install
    - run: npm run build:11ty
    - name: Upload website files
      uses: actions/upload-artifact@v4
      with:
        name: website
        path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Download website files
      uses: actions/download-artifact@v4
      with:
        name: website
        path: dist
    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        aws-region: us-east-1
        role-to-assume: ${{vars.CORE567_UPLOAD_ROLE_ARN}}
    - name: Upload files to S3 bucket
      run: aws s3 sync dist ${{vars.CORE567_BUCKET_NAME}} --delete
    - name: Invalidate Cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id ${{vars.CORE567_DISTRIBUTION_ID}} --paths '/*'
