name: Build website and publish to S3

on:
  push:
    branches: [ "main" ]

env:
  node-version: 22.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{env.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{env.node-version}}
        cache: 'npm'
    - run: npm install
    - run: npm run build:11ty
    - name: Upload website files
      uses: actions/upload-artifact@v4
      with:
        name: website
        path: dist/

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download website files
      uses: actions/downlaod-artifact@v4
      with:
        name: website
    - name: Display results
      run: ls -R dist

